apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    password: ${INFLUXDB_PASSWORD}
    user: ${INFLUXDB_USERNAME}
    database: telegraf
    basicAuth:
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault:
    version: 1
    editable: false
