image:
  repository: 211019955/stop-food-waste-model-api
  tag: latest
  pullPolicy: Always
  imagePullSecrets: []

configmap:
  data:
    DJANGO_SETTINGS_MODULE: config.settings.production

pvc:
  created: false
  storageClassName:

serviceAccount:
  created: false
  annotations: {}
  name:

djangoServer:
  replicaCount: 3

  command: ["gunicorn", "--workers", "1", "--bind", ":8000",
            "--log-level", "INFO", "config.wsgi"]

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8000

  hpa:
    enabled: false

  ingress:
    enabled: false
    annotations: {}

    hosts:
      - host: sfw-model-api.local
        paths: []
    tls: []

  probe:
    readiness:
      path: /
    liveness:
      path: /

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

