apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Release.Name}}-sfw-recipe
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Release.Name}}-sfw-recipe
  minReplicas: 1
  maxReplicas: 10
