apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{.Release.Name}}
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`recipe.sfw.io`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: {{.Release.Name}}
      port: 80
  tls:
    secretName: root-secret