apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sfwRecipe.service.type }}
  ports:
    - port: {{ .Values.sfwRecipe.service.port.http }}
      targetPort: django
      protocol: TCP
      name: django
    - port: {{ .Values.sfwRecipe.service.port.https }}
      targetPort: djangotls
      protocol: TCP
      name: djangotls
  selector:
    {{- include "django-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: sfw-recipe